import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { Box, Text } from 'ink';

// Color themes - edit these values to customize for each background type
// THEME_DARK is used when hasDarkBackground={true} (default)
// THEME_LIGHT is used when hasDarkBackground={false}
const THEME_DARK: Record<string, string> = {
  cyanBright: 'cyanBright',
  whiteBright: 'whiteBright',
};

const THEME_LIGHT: Record<string, string> = {
  cyanBright: 'cyan',
  whiteBright: 'blackBright',
};

type FrameData = {
  duration: number;
  content: string[];
  fgColors: Record<string, string>;
  bgColors: Record<string, string>;
};

type AsciiMotionCliProps = {
  hasDarkBackground?: boolean;
  autoPlay?: boolean;
  loop?: boolean;
};

const FRAMES: FrameData[] = [
  {
    "duration": 83.33333333333333,
    "content": [
      "                                                                                ",
      "                                                                                ",
      "     ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░          ",
      "     ░                                                               ░          ",
      "     ░                                                               ░          ",
      "     ░    ░░░░░░╗░░╗  ░░╗ ░░░░░╗  ░░░░░░╗ ░░░░░░░╗                   ░          ",
      "     ░   ░░╔════╝░░║  ░░║░░╔══░░╗░░╔═══░░╗░░╔════╝                   ░          ",
      "     ░   ░░║     ░░░░░░░║░░░░░░░║░░║   ░░║░░░░░░░╗                   ░          ",
      "     ░   ░░║     ░░╔══░░║░░╔══░░║░░║   ░░║╚════░░║                   ░          ",
      "     ░   ╚░░░░░░╗░░║  ░░║░░║  ░░║╚░░░░░░╔╝░░░░░░░║                   ░          ",
      "     ░    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝                   ░          ",
      "     ░                                                               ░          ",
      "     ░   ░░░░░░░░╗░░░░░░╗  ░░░░░╗  ░░░░░░╗░░╗  ░░╗░░░░░░░╗░░░░░░╗    ░          ",
      "     ░   ╚══░░╔══╝░░╔══░░╗░░╔══░░╗░░╔════╝░░║ ░░╔╝░░╔════╝░░╔══░░╗   ░          ",
      "     ░      ░░║   ░░░░░░╔╝░░░░░░░║░░║     ░░░░░╔╝ ░░░░░╗  ░░░░░░╔╝   ░          ",
      "     ░      ░░║   ░░╔══░░╗░░╔══░░║░░║     ░░╔═░░╗ ░░╔══╝  ░░╔══░░╗   ░          ",
      "     ░      ░░║   ░░║  ░░║░░║  ░░║╚░░░░░░╗░░║  ░░╗░░░░░░░╗░░║  ░░║   ░          ",
      "     ░      ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ░          ",
      "     ░                                                               ░          ",
      "     ░                                                               ░          ",
      "     ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░          ",
      "                                                                                ",
      "                                                                                ",
      "                                                                                "
    ],
    "fgColors": {
      "5,2": "cyanBright",
      "6,2": "cyanBright",
      "7,2": "cyanBright",
      "8,2": "cyanBright",
      "9,2": "cyanBright",
      "10,2": "cyanBright",
      "11,2": "cyanBright",
      "12,2": "cyanBright",
      "13,2": "cyanBright",
      "14,2": "cyanBright",
      "15,2": "cyanBright",
      "16,2": "cyanBright",
      "17,2": "cyanBright",
      "18,2": "cyanBright",
      "19,2": "cyanBright",
      "20,2": "cyanBright",
      "21,2": "cyanBright",
      "22,2": "cyanBright",
      "23,2": "cyanBright",
      "24,2": "cyanBright",
      "25,2": "cyanBright",
      "26,2": "cyanBright",
      "27,2": "cyanBright",
      "28,2": "cyanBright",
      "29,2": "cyanBright",
      "30,2": "cyanBright",
      "31,2": "cyanBright",
      "32,2": "cyanBright",
      "33,2": "cyanBright",
      "34,2": "cyanBright",
      "35,2": "cyanBright",
      "36,2": "cyanBright",
      "37,2": "cyanBright",
      "38,2": "cyanBright",
      "39,2": "cyanBright",
      "40,2": "cyanBright",
      "41,2": "cyanBright",
      "42,2": "cyanBright",
      "43,2": "cyanBright",
      "44,2": "cyanBright",
      "45,2": "cyanBright",
      "46,2": "cyanBright",
      "47,2": "cyanBright",
      "48,2": "cyanBright",
      "49,2": "cyanBright",
      "50,2": "cyanBright",
      "51,2": "cyanBright",
      "52,2": "cyanBright",
      "53,2": "cyanBright",
      "54,2": "cyanBright",
      "55,2": "cyanBright",
      "56,2": "cyanBright",
      "57,2": "cyanBright",
      "58,2": "cyanBright",
      "59,2": "cyanBright",
      "60,2": "cyanBright",
      "61,2": "cyanBright",
      "62,2": "cyanBright",
      "63,2": "cyanBright",
      "64,2": "cyanBright",
      "65,2": "cyanBright",
      "66,2": "cyanBright",
      "67,2": "cyanBright",
      "68,2": "cyanBright",
      "69,2": "cyanBright",
      "5,3": "cyanBright",
      "69,3": "cyanBright",
      "5,4": "cyanBright",
      "69,4": "cyanBright",
      "5,5": "cyanBright",
      "10,5": "cyanBright",
      "11,5": "cyanBright",
      "12,5": "cyanBright",
      "13,5": "cyanBright",
      "14,5": "cyanBright",
      "15,5": "cyanBright",
      "16,5": "whiteBright",
      "17,5": "cyanBright",
      "18,5": "cyanBright",
      "19,5": "whiteBright",
      "22,5": "cyanBright",
      "23,5": "cyanBright",
      "24,5": "whiteBright",
      "26,5": "cyanBright",
      "27,5": "cyanBright",
      "28,5": "cyanBright",
      "29,5": "cyanBright",
      "30,5": "cyanBright",
      "31,5": "whiteBright",
      "34,5": "cyanBright",
      "35,5": "cyanBright",
      "36,5": "cyanBright",
      "37,5": "cyanBright",
      "38,5": "cyanBright",
      "39,5": "cyanBright",
      "40,5": "whiteBright",
      "42,5": "cyanBright",
      "43,5": "cyanBright",
      "44,5": "cyanBright",
      "45,5": "cyanBright",
      "46,5": "cyanBright",
      "47,5": "cyanBright",
      "48,5": "cyanBright",
      "49,5": "whiteBright",
      "69,5": "cyanBright",
      "5,6": "cyanBright",
      "9,6": "cyanBright",
      "10,6": "cyanBright",
      "11,6": "whiteBright",
      "12,6": "whiteBright",
      "13,6": "whiteBright",
      "14,6": "whiteBright",
      "15,6": "whiteBright",
      "16,6": "whiteBright",
      "17,6": "cyanBright",
      "18,6": "cyanBright",
      "19,6": "whiteBright",
      "22,6": "cyanBright",
      "23,6": "cyanBright",
      "24,6": "whiteBright",
      "25,6": "cyanBright",
      "26,6": "cyanBright",
      "27,6": "whiteBright",
      "28,6": "whiteBright",
      "29,6": "whiteBright",
      "30,6": "cyanBright",
      "31,6": "cyanBright",
      "32,6": "whiteBright",
      "33,6": "cyanBright",
      "34,6": "cyanBright",
      "35,6": "whiteBright",
      "36,6": "whiteBright",
      "37,6": "whiteBright",
      "38,6": "whiteBright",
      "39,6": "cyanBright",
      "40,6": "cyanBright",
      "41,6": "whiteBright",
      "42,6": "cyanBright",
      "43,6": "cyanBright",
      "44,6": "whiteBright",
      "45,6": "whiteBright",
      "46,6": "whiteBright",
      "47,6": "whiteBright",
      "48,6": "whiteBright",
      "49,6": "whiteBright",
      "69,6": "cyanBright",
      "5,7": "cyanBright",
      "9,7": "cyanBright",
      "10,7": "cyanBright",
      "11,7": "whiteBright",
      "17,7": "cyanBright",
      "18,7": "cyanBright",
      "19,7": "cyanBright",
      "20,7": "cyanBright",
      "21,7": "cyanBright",
      "22,7": "cyanBright",
      "23,7": "cyanBright",
      "24,7": "whiteBright",
      "25,7": "cyanBright",
      "26,7": "cyanBright",
      "27,7": "cyanBright",
      "28,7": "cyanBright",
      "29,7": "cyanBright",
      "30,7": "cyanBright",
      "31,7": "cyanBright",
      "32,7": "whiteBright",
      "33,7": "cyanBright",
      "34,7": "cyanBright",
      "35,7": "whiteBright",
      "39,7": "cyanBright",
      "40,7": "cyanBright",
      "41,7": "whiteBright",
      "42,7": "cyanBright",
      "43,7": "cyanBright",
      "44,7": "cyanBright",
      "45,7": "cyanBright",
      "46,7": "cyanBright",
      "47,7": "cyanBright",
      "48,7": "cyanBright",
      "49,7": "whiteBright",
      "69,7": "cyanBright",
      "5,8": "cyanBright",
      "9,8": "cyanBright",
      "10,8": "cyanBright",
      "11,8": "whiteBright",
      "17,8": "cyanBright",
      "18,8": "cyanBright",
      "19,8": "whiteBright",
      "20,8": "whiteBright",
      "21,8": "whiteBright",
      "22,8": "cyanBright",
      "23,8": "cyanBright",
      "24,8": "whiteBright",
      "25,8": "cyanBright",
      "26,8": "cyanBright",
      "27,8": "whiteBright",
      "28,8": "whiteBright",
      "29,8": "whiteBright",
      "30,8": "cyanBright",
      "31,8": "cyanBright",
      "32,8": "whiteBright",
      "33,8": "cyanBright",
      "34,8": "cyanBright",
      "35,8": "whiteBright",
      "39,8": "cyanBright",
      "40,8": "cyanBright",
      "41,8": "whiteBright",
      "42,8": "whiteBright",
      "43,8": "whiteBright",
      "44,8": "whiteBright",
      "45,8": "whiteBright",
      "46,8": "whiteBright",
      "47,8": "cyanBright",
      "48,8": "cyanBright",
      "49,8": "whiteBright",
      "69,8": "cyanBright",
      "5,9": "cyanBright",
      "9,9": "whiteBright",
      "10,9": "cyanBright",
      "11,9": "cyanBright",
      "12,9": "cyanBright",
      "13,9": "cyanBright",
      "14,9": "cyanBright",
      "15,9": "cyanBright",
      "16,9": "whiteBright",
      "17,9": "cyanBright",
      "18,9": "cyanBright",
      "19,9": "whiteBright",
      "22,9": "cyanBright",
      "23,9": "cyanBright",
      "24,9": "whiteBright",
      "25,9": "cyanBright",
      "26,9": "cyanBright",
      "27,9": "whiteBright",
      "30,9": "cyanBright",
      "31,9": "cyanBright",
      "32,9": "whiteBright",
      "33,9": "whiteBright",
      "34,9": "cyanBright",
      "35,9": "cyanBright",
      "36,9": "cyanBright",
      "37,9": "cyanBright",
      "38,9": "cyanBright",
      "39,9": "cyanBright",
      "40,9": "whiteBright",
      "41,9": "whiteBright",
      "42,9": "cyanBright",
      "43,9": "cyanBright",
      "44,9": "cyanBright",
      "45,9": "cyanBright",
      "46,9": "cyanBright",
      "47,9": "cyanBright",
      "48,9": "cyanBright",
      "49,9": "whiteBright",
      "69,9": "cyanBright",
      "5,10": "cyanBright",
      "10,10": "whiteBright",
      "11,10": "whiteBright",
      "12,10": "whiteBright",
      "13,10": "whiteBright",
      "14,10": "whiteBright",
      "15,10": "whiteBright",
      "16,10": "whiteBright",
      "17,10": "whiteBright",
      "18,10": "whiteBright",
      "19,10": "whiteBright",
      "22,10": "whiteBright",
      "23,10": "whiteBright",
      "24,10": "whiteBright",
      "25,10": "whiteBright",
      "26,10": "whiteBright",
      "27,10": "whiteBright",
      "30,10": "whiteBright",
      "31,10": "whiteBright",
      "32,10": "whiteBright",
      "34,10": "whiteBright",
      "35,10": "whiteBright",
      "36,10": "whiteBright",
      "37,10": "whiteBright",
      "38,10": "whiteBright",
      "39,10": "whiteBright",
      "40,10": "whiteBright",
      "42,10": "whiteBright",
      "43,10": "whiteBright",
      "44,10": "whiteBright",
      "45,10": "whiteBright",
      "46,10": "whiteBright",
      "47,10": "whiteBright",
      "48,10": "whiteBright",
      "49,10": "whiteBright",
      "69,10": "cyanBright",
      "5,11": "cyanBright",
      "69,11": "cyanBright",
      "5,12": "cyanBright",
      "9,12": "cyanBright",
      "10,12": "cyanBright",
      "11,12": "cyanBright",
      "12,12": "cyanBright",
      "13,12": "cyanBright",
      "14,12": "cyanBright",
      "15,12": "cyanBright",
      "16,12": "cyanBright",
      "17,12": "whiteBright",
      "18,12": "cyanBright",
      "19,12": "cyanBright",
      "20,12": "cyanBright",
      "21,12": "cyanBright",
      "22,12": "cyanBright",
      "23,12": "cyanBright",
      "24,12": "whiteBright",
      "27,12": "cyanBright",
      "28,12": "cyanBright",
      "29,12": "cyanBright",
      "30,12": "cyanBright",
      "31,12": "cyanBright",
      "32,12": "whiteBright",
      "35,12": "cyanBright",
      "36,12": "cyanBright",
      "37,12": "cyanBright",
      "38,12": "cyanBright",
      "39,12": "cyanBright",
      "40,12": "cyanBright",
      "41,12": "whiteBright",
      "42,12": "cyanBright",
      "43,12": "cyanBright",
      "44,12": "whiteBright",
      "47,12": "cyanBright",
      "48,12": "cyanBright",
      "49,12": "whiteBright",
      "50,12": "cyanBright",
      "51,12": "cyanBright",
      "52,12": "cyanBright",
      "53,12": "cyanBright",
      "54,12": "cyanBright",
      "55,12": "cyanBright",
      "56,12": "cyanBright",
      "57,12": "whiteBright",
      "58,12": "cyanBright",
      "59,12": "cyanBright",
      "60,12": "cyanBright",
      "61,12": "cyanBright",
      "62,12": "cyanBright",
      "63,12": "cyanBright",
      "64,12": "whiteBright",
      "69,12": "cyanBright",
      "5,13": "cyanBright",
      "9,13": "whiteBright",
      "10,13": "whiteBright",
      "11,13": "whiteBright",
      "12,13": "cyanBright",
      "13,13": "cyanBright",
      "14,13": "whiteBright",
      "15,13": "whiteBright",
      "16,13": "whiteBright",
      "17,13": "whiteBright",
      "18,13": "cyanBright",
      "19,13": "cyanBright",
      "20,13": "whiteBright",
      "21,13": "whiteBright",
      "22,13": "whiteBright",
      "23,13": "cyanBright",
      "24,13": "cyanBright",
      "25,13": "whiteBright",
      "26,13": "cyanBright",
      "27,13": "cyanBright",
      "28,13": "whiteBright",
      "29,13": "whiteBright",
      "30,13": "whiteBright",
      "31,13": "cyanBright",
      "32,13": "cyanBright",
      "33,13": "whiteBright",
      "34,13": "cyanBright",
      "35,13": "cyanBright",
      "36,13": "whiteBright",
      "37,13": "whiteBright",
      "38,13": "whiteBright",
      "39,13": "whiteBright",
      "40,13": "whiteBright",
      "41,13": "whiteBright",
      "42,13": "cyanBright",
      "43,13": "cyanBright",
      "44,13": "whiteBright",
      "46,13": "cyanBright",
      "47,13": "cyanBright",
      "48,13": "whiteBright",
      "49,13": "whiteBright",
      "50,13": "cyanBright",
      "51,13": "cyanBright",
      "52,13": "whiteBright",
      "53,13": "whiteBright",
      "54,13": "whiteBright",
      "55,13": "whiteBright",
      "56,13": "whiteBright",
      "57,13": "whiteBright",
      "58,13": "cyanBright",
      "59,13": "cyanBright",
      "60,13": "whiteBright",
      "61,13": "whiteBright",
      "62,13": "whiteBright",
      "63,13": "cyanBright",
      "64,13": "cyanBright",
      "65,13": "whiteBright",
      "69,13": "cyanBright",
      "5,14": "cyanBright",
      "12,14": "cyanBright",
      "13,14": "cyanBright",
      "14,14": "whiteBright",
      "18,14": "cyanBright",
      "19,14": "cyanBright",
      "20,14": "cyanBright",
      "21,14": "cyanBright",
      "22,14": "cyanBright",
      "23,14": "cyanBright",
      "24,14": "whiteBright",
      "25,14": "whiteBright",
      "26,14": "cyanBright",
      "27,14": "cyanBright",
      "28,14": "cyanBright",
      "29,14": "cyanBright",
      "30,14": "cyanBright",
      "31,14": "cyanBright",
      "32,14": "cyanBright",
      "33,14": "whiteBright",
      "34,14": "cyanBright",
      "35,14": "cyanBright",
      "36,14": "whiteBright",
      "42,14": "cyanBright",
      "43,14": "cyanBright",
      "44,14": "cyanBright",
      "45,14": "cyanBright",
      "46,14": "cyanBright",
      "47,14": "whiteBright",
      "48,14": "whiteBright",
      "50,14": "cyanBright",
      "51,14": "cyanBright",
      "52,14": "cyanBright",
      "53,14": "cyanBright",
      "54,14": "cyanBright",
      "55,14": "whiteBright",
      "58,14": "cyanBright",
      "59,14": "cyanBright",
      "60,14": "cyanBright",
      "61,14": "cyanBright",
      "62,14": "cyanBright",
      "63,14": "cyanBright",
      "64,14": "whiteBright",
      "65,14": "whiteBright",
      "69,14": "cyanBright",
      "5,15": "cyanBright",
      "12,15": "cyanBright",
      "13,15": "cyanBright",
      "14,15": "whiteBright",
      "18,15": "cyanBright",
      "19,15": "cyanBright",
      "20,15": "whiteBright",
      "21,15": "whiteBright",
      "22,15": "whiteBright",
      "23,15": "cyanBright",
      "24,15": "cyanBright",
      "25,15": "whiteBright",
      "26,15": "cyanBright",
      "27,15": "cyanBright",
      "28,15": "whiteBright",
      "29,15": "whiteBright",
      "30,15": "whiteBright",
      "31,15": "cyanBright",
      "32,15": "cyanBright",
      "33,15": "whiteBright",
      "34,15": "cyanBright",
      "35,15": "cyanBright",
      "36,15": "whiteBright",
      "42,15": "cyanBright",
      "43,15": "cyanBright",
      "44,15": "whiteBright",
      "45,15": "whiteBright",
      "46,15": "cyanBright",
      "47,15": "cyanBright",
      "48,15": "whiteBright",
      "50,15": "cyanBright",
      "51,15": "cyanBright",
      "52,15": "whiteBright",
      "53,15": "whiteBright",
      "54,15": "whiteBright",
      "55,15": "whiteBright",
      "58,15": "cyanBright",
      "59,15": "cyanBright",
      "60,15": "whiteBright",
      "61,15": "whiteBright",
      "62,15": "whiteBright",
      "63,15": "cyanBright",
      "64,15": "cyanBright",
      "65,15": "whiteBright",
      "69,15": "cyanBright",
      "5,16": "cyanBright",
      "12,16": "cyanBright",
      "13,16": "cyanBright",
      "14,16": "whiteBright",
      "18,16": "cyanBright",
      "19,16": "cyanBright",
      "20,16": "whiteBright",
      "23,16": "cyanBright",
      "24,16": "cyanBright",
      "25,16": "whiteBright",
      "26,16": "cyanBright",
      "27,16": "cyanBright",
      "28,16": "whiteBright",
      "31,16": "cyanBright",
      "32,16": "cyanBright",
      "33,16": "whiteBright",
      "34,16": "whiteBright",
      "35,16": "cyanBright",
      "36,16": "cyanBright",
      "37,16": "cyanBright",
      "38,16": "cyanBright",
      "39,16": "cyanBright",
      "40,16": "cyanBright",
      "41,16": "whiteBright",
      "42,16": "cyanBright",
      "43,16": "cyanBright",
      "44,16": "whiteBright",
      "47,16": "cyanBright",
      "48,16": "cyanBright",
      "49,16": "whiteBright",
      "50,16": "cyanBright",
      "51,16": "cyanBright",
      "52,16": "cyanBright",
      "53,16": "cyanBright",
      "54,16": "cyanBright",
      "55,16": "cyanBright",
      "56,16": "cyanBright",
      "57,16": "whiteBright",
      "58,16": "cyanBright",
      "59,16": "cyanBright",
      "60,16": "whiteBright",
      "63,16": "cyanBright",
      "64,16": "cyanBright",
      "65,16": "whiteBright",
      "69,16": "cyanBright",
      "5,17": "cyanBright",
      "12,17": "whiteBright",
      "13,17": "whiteBright",
      "14,17": "whiteBright",
      "18,17": "whiteBright",
      "19,17": "whiteBright",
      "20,17": "whiteBright",
      "23,17": "whiteBright",
      "24,17": "whiteBright",
      "25,17": "whiteBright",
      "26,17": "whiteBright",
      "27,17": "whiteBright",
      "28,17": "whiteBright",
      "31,17": "whiteBright",
      "32,17": "whiteBright",
      "33,17": "whiteBright",
      "35,17": "whiteBright",
      "36,17": "whiteBright",
      "37,17": "whiteBright",
      "38,17": "whiteBright",
      "39,17": "whiteBright",
      "40,17": "whiteBright",
      "41,17": "whiteBright",
      "42,17": "whiteBright",
      "43,17": "whiteBright",
      "44,17": "whiteBright",
      "47,17": "whiteBright",
      "48,17": "whiteBright",
      "49,17": "whiteBright",
      "50,17": "whiteBright",
      "51,17": "whiteBright",
      "52,17": "whiteBright",
      "53,17": "whiteBright",
      "54,17": "whiteBright",
      "55,17": "whiteBright",
      "56,17": "whiteBright",
      "57,17": "whiteBright",
      "58,17": "whiteBright",
      "59,17": "whiteBright",
      "60,17": "whiteBright",
      "63,17": "whiteBright",
      "64,17": "whiteBright",
      "65,17": "whiteBright",
      "69,17": "cyanBright",
      "5,18": "cyanBright",
      "69,18": "cyanBright",
      "5,19": "cyanBright",
      "69,19": "cyanBright",
      "5,20": "cyanBright",
      "6,20": "cyanBright",
      "7,20": "cyanBright",
      "8,20": "cyanBright",
      "9,20": "cyanBright",
      "10,20": "cyanBright",
      "11,20": "cyanBright",
      "12,20": "cyanBright",
      "13,20": "cyanBright",
      "14,20": "cyanBright",
      "15,20": "cyanBright",
      "16,20": "cyanBright",
      "17,20": "cyanBright",
      "18,20": "cyanBright",
      "19,20": "cyanBright",
      "20,20": "cyanBright",
      "21,20": "cyanBright",
      "22,20": "cyanBright",
      "23,20": "cyanBright",
      "24,20": "cyanBright",
      "25,20": "cyanBright",
      "26,20": "cyanBright",
      "27,20": "cyanBright",
      "28,20": "cyanBright",
      "29,20": "cyanBright",
      "30,20": "cyanBright",
      "31,20": "cyanBright",
      "32,20": "cyanBright",
      "33,20": "cyanBright",
      "34,20": "cyanBright",
      "35,20": "cyanBright",
      "36,20": "cyanBright",
      "37,20": "cyanBright",
      "38,20": "cyanBright",
      "39,20": "cyanBright",
      "40,20": "cyanBright",
      "41,20": "cyanBright",
      "42,20": "cyanBright",
      "43,20": "cyanBright",
      "44,20": "cyanBright",
      "45,20": "cyanBright",
      "46,20": "cyanBright",
      "47,20": "cyanBright",
      "48,20": "cyanBright",
      "49,20": "cyanBright",
      "50,20": "cyanBright",
      "51,20": "cyanBright",
      "52,20": "cyanBright",
      "53,20": "cyanBright",
      "54,20": "cyanBright",
      "55,20": "cyanBright",
      "56,20": "cyanBright",
      "57,20": "cyanBright",
      "58,20": "cyanBright",
      "59,20": "cyanBright",
      "60,20": "cyanBright",
      "61,20": "cyanBright",
      "62,20": "cyanBright",
      "63,20": "cyanBright",
      "64,20": "cyanBright",
      "65,20": "cyanBright",
      "66,20": "cyanBright",
      "67,20": "cyanBright",
      "68,20": "cyanBright",
      "69,20": "cyanBright"
    },
    "bgColors": {}
  }
];

const CANVAS_WIDTH = 80;
const CANVAS_HEIGHT = 24;
const DEFAULT_LOOP = false;

export const AsciiMotionCli: React.FC<AsciiMotionCliProps> = ({
  hasDarkBackground = true,
  autoPlay = true,
  loop = DEFAULT_LOOP,
}) => {
  const [frameIndex, setFrameIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(autoPlay);
  const frameElapsedRef = useRef(0);
  const lastTimestampRef = useRef(Date.now());

  // Select color theme based on background
  const theme = useMemo(() => hasDarkBackground ? THEME_DARK : THEME_LIGHT, [hasDarkBackground]);
  const getColor = useCallback((key: string): string => theme[key] || key, [theme]);
  const defaultFg = hasDarkBackground ? "white" : "black";

  const play = useCallback(() => setIsPlaying(true), []);
  const pause = useCallback(() => setIsPlaying(false), []);
  const restart = useCallback(() => {
    setFrameIndex(0);
    frameElapsedRef.current = 0;
    lastTimestampRef.current = Date.now();
    setIsPlaying(true);
  }, []);

  useEffect(() => {
    if (!isPlaying || FRAMES.length <= 1) return;

    const interval = setInterval(() => {
      const now = Date.now();
      const delta = now - lastTimestampRef.current;
      lastTimestampRef.current = now;
      frameElapsedRef.current += delta;

      const currentFrame = FRAMES[frameIndex];
      if (frameElapsedRef.current >= currentFrame.duration) {
        frameElapsedRef.current = 0;
        const nextIndex = frameIndex + 1;
        if (nextIndex >= FRAMES.length) {
          if (loop) {
            setFrameIndex(0);
          } else {
            setIsPlaying(false);
          }
        } else {
          setFrameIndex(nextIndex);
        }
      }
    }, 16);

    return () => clearInterval(interval);
  }, [isPlaying, frameIndex, loop]);

  const frame = FRAMES[frameIndex];

  return (
    <Box flexDirection="column">
      {frame.content.map((row, y) => (
        <Box key={y}>
          {row.split("").map((char, x) => {
            const posKey = `${x},${y}`;
            const fg = frame.fgColors[posKey] ? getColor(frame.fgColors[posKey]) : defaultFg;
            const bg = frame.bgColors[posKey] ? getColor(frame.bgColors[posKey]) : undefined;
            return (
              <Text key={x} color={fg} backgroundColor={bg}>
                {char}
              </Text>
            );
          })}
        </Box>
      ))}
    </Box>
  );
};

export default AsciiMotionCli;
